version: '3.8'

services:
  broker_mqtt:
    image: eclipse-mosquitto:latest
    container_name: broker_mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: always
    networks:
      - luflex_net

  nodered_luflex:
    image: nodered/node-red:latest
    container_name: nodered
    user: "root"
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
      - ./flows.json:/data/flows.json
    # 🚀 RUTA CORREGIDA: Se para en la carpeta del proyecto, instala local y arranca de forma nativa
    entrypoint: ["bash", "-c", "cd /usr/src/node-red && npm install node-red-dashboard && ./entrypoint.sh"]
    restart: always
    networks:
      - luflex_net

volumes:
  nodered_data:
  mosquitto_data:
  mosquitto_log:

networks:
  luflex_net:
    driver: bridge